# Introduction to Numpy


 ## What is Numpy ?

*NumPy is a powerful Python library that is used for arrays, matrices, and numerical calculations.*

## Installation of numpy

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


pip install numpy is a command that is used to install the NumPy library in Python.

## Import Numpy Library

In [3]:
import numpy as np


#### Loading the NumPy library in a Python program and giving it a short name np.

* import :- means bringing a library into the program

* numpy :- is a Python library used for numbers, arrays, and mathematical operations

* as np :- means giving NumPy a short name np

In [4]:
# print(dir(np))

## Numpy Array

### **1D Array**

*This is a one-dimensional array. It has only one row.*

#### **print(arr)** = *Prints all the elements of the array.*


In [5]:
arr = np.array([11,12,13,14,15,16,17])
print(arr)

[11 12 13 14 15 16 17]


### **2D Array (Matrix)**

*This is a 2D array. It has rows and columns.*


In [6]:
arr1 = np.array([[12,13,14,11],[15,124,15,15],[21,4,54,54]])
print(arr1)

[[ 12  13  14  11]
 [ 15 124  15  15]
 [ 21   4  54  54]]


### **3D Array (Single Block)**

*This is a 3D array, meaning: 1 block, 4 rows, and 3 columns.*


In [7]:
arr2 = np.array([[[12,12,12],[11,42,52],[43,45,98],[3,5,5]]])
print(arr2)

[[[12 12 12]
  [11 42 52]
  [43 45 98]
  [ 3  5  5]]]


### **3D Array (Multiple Blocks)**

*When an array contains multiple 2D matrices (layers) inside it, it is called multiple blocks.*


In [8]:
arr3 = np.array([[[45,22,45,15],[58,54,55,45]],
                 [[45,84,43,54],[75,45,65,58]]])
print(arr3)

[[[45 22 45 15]
  [58 54 55 45]]

 [[45 84 43 54]
  [75 45 65 58]]]


### Array Indexing & Properties

**print(arr1)** :- *Prints all the elements of the array.*


In [10]:
arr1 = np.array([[[12,13,14,11],[15,124,15,15]],[[21,4,54,54],[54,54,24,78]]])
print(type(arr1)) 

<class 'numpy.ndarray'>


**type** :- *It tells the data type of the array.*


In [11]:
arr1 = np.array([[[12,13,14,11],[15,124,15,15]],[[21,4,54,54],[54,54,24,78]]])
print(arr1.ndim)

3


**ndim** :- *It tells the number of dimensions of the array.*


In [13]:
arr1 = np.array([[[12,13,14,11],[15,124,15,15]],[[21,4,54,54],[54,54,24,78]]])
print(arr1.shape)

(2, 2, 4)


**Shape** :- *Meaning: 2 blocks (layers), each block has 2 rows, and each row has 4 columns.*


In [14]:
arr1 = np.array([[[12,13,14,11],[15,124,15,15]],[[21,4,54,54],[54,54,24,78]]])
print(arr1.size)

16


**size** :- *Counts the total number of elements.*
**Formula:** blocks × rows × columns = 2 × 2 × 4 = **16**


## **NumPy Functions**

##### **Array Creation Functions** :- (array, zeros, ones, eye, full)

##### **Mathematical Functions** :- (sum, mean, max, min, sqrt)

##### **Shape & Dimension Functions** :- (ndim, shape, size)

##### **Random Functions** :- (random.rand, random.randint, random.randn)

##### **Sequence Functions** :- (arange, linspace)

##### **Matrix Functions** :- (dot, transpose)



### Array Creation Functions :-

In [15]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

**Array** :- *An array is the main data structure of NumPy. It stores multiple values in a single variable, and all values are of the same data type.*


In [18]:
arr = np.zeros((5,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**Ones** :- *When we want to initialize an array with the default value 1, we use `ones()`.*


In [20]:
arr = np.eye(3,4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

**eye** :- *An identity matrix is a matrix in which the diagonal elements are 1, and all other elements are 0.*


In [21]:
arr = np.full((3,4), 9)
arr

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

**full** :- *Fills every element of the array with the same value for the given size.*


### Mathematical Functions :-

In [22]:
arr = np.array([10, 20, 30, 40])
print(arr.sum())

100


**sum** :- *Gives the sum of all the values present in the array at once.*


In [23]:
arr = np.array([10, 20, 30, 40])
print(arr.mean())


25.0


**mean** :- *A NumPy function that calculates the average (arithmetic mean) of an array.*
**Formula:** Mean = (Sum of all values) ÷ (Total number of values)


In [25]:
arr = np.array([10, 45, 23, 90, 12])
print(arr.max())

90


**max** :- *Finds the largest (maximum) value in the array.*


In [26]:
arr = np.array([10, 45, 23, 90, 12])
print(arr.min())

10


**min** :- *Finds the smallest (minimum) value in the array.*


In [27]:
arr = np.array([1, 4, 9, 16, 25])
print(np.sqrt(arr))

[1. 2. 3. 4. 5.]


**sqrt** :- *Calculates the square root of each element in the array.*


### Shape & Dimension Functions :-

In [28]:
arr = np.array([10, 20, 30])
print(arr.ndim)

1


**ndim** :- *Tells the total number of dimensions of the array.*


In [29]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


**shape** :- *Tells the structure or size of the array (rows, columns, blocks).*


In [31]:
arr = np.array([10, 20, 30, 40])
print(arr.size)

4


**size** :- *Tells the total number of elements in the array.*


### Random Functions :- (random.rand,random.randint,random.randn)

In [32]:
arr = np.random.rand(3,3)
print(arr)

[[0.574553   0.50352624 0.09540255]
 [0.18947717 0.99865914 0.43269718]
 [0.14464916 0.98005067 0.1150863 ]]


**random.rand** :- *A NumPy function that generates random numbers between 0 and 1 (positive values).*


In [49]:
arr = np.random.randint(10,100,(4,3))
print(arr)

[[30 31 37]
 [16 89 80]
 [91 46 77]
 [64 11 66]]


**random.randint** :- *Generates random integers within a specified range.*
**Example Range:** (10, 100)


In [34]:
arr = np.random.randn(10)
print(arr)

[-1.86194289  0.94026419 -0.44513522 -0.55778056  0.48357019 -0.34236168
  0.49707133 -0.22582418 -1.33398739  0.8902725 ]


**random.randn** :- *Generates normally distributed (Gaussian) random numbers. These numbers can be both negative and positive, generally around a mean of 0 and standard deviation of 1.*


### Sequence Functions :- 

In [35]:
arr = np.arange(0, 40, 2)   # (start, stop, step)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]


**arange** :- *Generates numbers from start to stop with a specified step.*


In [50]:
arr = np.linspace(0,20,5)  # (start,stop num)
print(arr)

[ 0.  5. 10. 15. 20.]


**linspace** :- *Generates evenly spaced numbers between a specified start and stop.*


### Matrix Functions :- 

In [37]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.dot(a, b)
print(result)

32


**dot** :- *Performs the dot product (sum of products) or matrix multiplication.*


In [38]:
arr= np.array([[1, 2, 3],[4, 5, 6]])
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


**transpose (T)** :- *Swaps the rows and columns of a matrix.*


In [39]:
arr = np.array([10, 45, 23, 99, 34])
print(np.argmax(arr))

3


**argmax()** :- *A NumPy function that returns the index position of the largest (maximum) value in the array.*


In [40]:
arr = np.array([10, 45, 23, 5, 34])
print(np.argmin(arr))

3


**argmin()** :- *A NumPy function that returns the index position of the smallest (minimum) value in the array.*


In [41]:
arr = np.array([10, 20, 30, 40, 50])
print(np.std(arr))

14.142135623730951


**std()** :- *A NumPy function that calculates the standard deviation. It measures how much the data is spread out or deviates from the mean (average).*


In [42]:
arr = np.array([[1, 2, 3],[4, 5, 6]])
print(arr.flatten())

[1 2 3 4 5 6]


**flatten()** :- *A NumPy function that converts a multi-dimensional array (2D, 3D, etc.) into a 1D array.*


In [43]:
arr = np.array([[1, 2, 3],[4, 5, 6]])
print(arr.ravel())

[1 2 3 4 5 6]


**ravel()** :- *Flattens the array, but in most cases returns a “view” of the original array rather than a copy.*


In [44]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.reshape(2, 3))

[[1 2 3]
 [4 5 6]]


**reshape()** :- *A NumPy function that changes the shape of an array. The data remains the same; only the rows–columns structure is modified.*


In [45]:
arr = np.array([1, 2, 3, 4])
print(np.diag(arr))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


**diag()** :- *A NumPy function that works with the diagonal elements of an array or matrix.*


### Arithmetic Operations

In [46]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
print(a + b)

print(a - b)

print(a * b)

print(a / b)

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]


### Sort Array

In [48]:
 arr = np.array([40, 10, 30, 20])
print(np.sort(arr))

[10 20 30 40]


## Difference Between NumPy Array and Python List

| Feature                  | Python List                                                              | NumPy Array                                                                                          |
| ------------------------ | ------------------------------------------------------------------------ | ---------------------------------------------------------------------------------------------------- |
| **Performance**          | Slower for numerical computations due to per-element overhead            | Much faster for large-scale mathematical operations                                                  |
| **Mathematical Support** | Limited to general-purpose methods like `sort()`, `count()`, `reverse()` | Supports advanced mathematical functions, linear algebra, broadcasting, and multi-dimensional arrays |
| **Data Type**            | Can store mixed data types in a single list                              | All elements must be of the same data type                                                           |
| **Memory Efficiency**    | Less memory efficient                                                    | More memory efficient for numerical data                                                             |
| **Usage**                | General-purpose container                                                | Optimized for scientific and numerical computing                                                     |


*In Python, both lists and NumPy arrays are used to store data. Their functionality may seem similar, but there is a significant difference in performance, usage, and capability.*

*NumPy performs faster for large-scale mathematical operations, while lists are slower for numerical computations due to per-element overhead.*

*NumPy supports advanced mathematical functions, linear algebra, broadcasting, and multi-dimensional arrays, whereas lists offer general-purpose methods like sort, count, and reverse.*


In [52]:
list1 = [1, 2, 3, 4]
array1 = np.array([1,2,3,4])
print("List Addition: ",list1 + list1)
print("Numpy array Addition : ", array1 +array1)


List Addition:  [1, 2, 3, 4, 1, 2, 3, 4]
Numpy array Addition :  [2 4 6 8]


*Lists repeat or concatenate the values, whereas NumPy arrays perform element-wise addition and return the sum of values.*
